### ISSUE TITLE
Benchmarking

### ISSUE THREAD

**Issue by simbilod** [simbilod/optio#6]
There are still deviations between nominally identical geometries and simulations defined in this package and Lumerical

![output](https://user-images.githubusercontent.com/46427609/149680247-ff74d4c7-2b56-4472-960f-c35ba660847a.png)

**Comment by simbilod** [comment]
Since the main deviation is lateral offsetting of the tranmission and reflection peaks, there could be a slight effective periodicity offset between the two simulations.

**Comment by simbilod** [comment]
Since both the transmission (S12) and waveguide reflection (S11) peaks are shifted, this is more likely due to some effective periodicity or index difference rather than some translational or angular misalignment of fiber/fiber port.

**Comment by simbilod** [comment]
When turning subpixel averaging off (epsOff), the match is much closer (at least in terms of bandwidth and center frequency). I will chalk the difference between Lumerical and MEEP to something internal.

![output2](https://user-images.githubusercontent.com/46427609/149682448-ae9edd45-c70f-41f0-9999-622228a10315.png)

**Comment by joamatab** [comment]
Looks quite close to me, are you using dispersive materials in keep?

**Comment by simbilod** [comment]
This was done with constant indices for both MEEP and Lumerical. All other geometry and simulation parameters are made as identical as possible (uniform grid of same resolution, geometries, source and monitor settings).
